# Use Node and Python providers
providers = ["node", "python"]

[phases.setup]
# ffmpeg is required for video streaming
nixPkgs = ["ffmpeg"]

# No need to define install/build cmds, providers will handle them automatically
